---
name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: 0 1 * * *
  workflow_dispatch: {}

permissions: {}

jobs:
  build:
    strategy:
      matrix:
        python-version: ['3.13']
        platform: [ubuntu-latest, windows-latest]
        hook-stage: [pre-commit, pre-push, manual]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Checkout proposed typeshed stubs
        if: github.event_name == 'pull_request' && github.head_ref == 'demo/docutils-typed-options'
        uses: actions/checkout@v7
        with:
          repository: adamtheturtle/typeshed
          ref: docutils-generic-options
          path: .typeshed-preview
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v10.1.0
        with:
          enable-cache: true
          cache-dependency-glob: '**/pyproject.toml'
          cache-suffix: ${{ matrix.python-version }}-${{ matrix.platform }}-${{ matrix.hook-stage
            }}
          save-cache: ${{ github.event_name != 'pull_request' }}

      - name: Use proposed Docutils stub
        if: github.event_name == 'pull_request' && github.head_ref == 'demo/docutils-typed-options'
        env:
          UV_PYTHON: ${{ matrix.python-version }}
        run: >-
          uv sync --locked --group=dev &&
          uv run --group=dev python -c
          'from importlib.metadata import distribution;
          from pathlib import Path;
          from shutil import copyfile;
          copyfile(
          Path(".typeshed-preview/stubs/docutils/docutils/parsers/rst/__init__.pyi"),
          distribution("types-docutils").locate_file("docutils-stubs/parsers/rst/__init__.pyi"))'

      - name: Lint
        uses: j178/prek-action@v3.0.0
        with:
          prek-version: 0.4.11
          extra-args: >-
            --all-files --hook-stage ${{ matrix.hook-stage }} --verbose
        env:
          UV_NO_CACHE: '1'
          UV_PYTHON: ${{ matrix.python-version }}

  completion-lint:
    needs: build
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Check matrix job status
        run: |-
          if ! ${{ needs.build.result == 'success' }}; then
            echo "One or more matrix jobs failed"
            exit 1
          fi
